disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "rss"]

[module]
  replacements = "github.com/lehmannro/hugo-datatable -> ../.."

  [[module.imports]]
    path = "github.com/lehmannro/hugo-datatable"
